### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by mozzer502** [getterdone/FlumeWaterMeter#2]
hey. I'm new to this so apologies in advance for noob questions.
I've created and published the device handler. Everything seems fine.
I've created and published the smart app. In the IDE I set the keys, and turned on Oauth.
In the mobile app, I've filled out the preferences sections.
Now how do I use this? I'm trying to create a rule that says If leak detected, turn off water but the app doesn't appear as a device in the Automations section.
Any ideas?

**Comment by getterdone** [comment]
Hi, the device not being selectable might have been due to the transition from Legacy Smartthings (Classic) app to new framework being used for Smartthings OneApp.

The device is now selectable as a Sensor in the new Smartthings OneApp.
Smartthings OneApp Steps:
Click the plus + symbol. Select Automation, Add your condition (find the Flume water sensor) select Wet. 
Then Add your Action. Select the device you are using to turn off your water valve, select Off. Save automation (Click Done).
